name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  build:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Cache OpenCV Android SDK
        id: cache-opencv
        uses: actions/cache@v4
        with:
          path: opencv
          key: opencv-android-sdk-4.12.0

      - name: Download OpenCV Android SDK
        if: steps.cache-opencv.outputs.cache-hit != 'true'
        run: |
          curl -L https://github.com/opencv/opencv/releases/download/4.12.0/opencv-4.12.0-android-sdk.zip -o opencv.zip
          unzip -q opencv.zip
          mv OpenCV-android-sdk/sdk/native opencv/native
          rm -rf opencv.zip OpenCV-android-sdk

      - name: Set up local.properties
        run: |
          echo "opencv.dir=$PWD/opencv" >> local.properties

      - name: Set up JDK environment
        uses: actions/setup-java@v4
        with:
          java-version-file: ".tool-versions"
          distribution: "temurin"
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle Wrapper
        uses: actions/cache@v4
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-wrapper-

      - name: Cache Gradle Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-caches-

      - name: Build Android app bundle
        run: ./gradlew app:bundle
